### ISSUE TITLE
Problems with custom primary keys

### ISSUE THREAD

**Issue by Patrick-Berg** [linuxlewis/channels-api#12]
If you don't use the default django primary key for your models and instead use "ID = models.AutoField(primary_key=True)" for example there are two problems.

Firstly id = instance.id in the bindings.py will throw an error because you don't have the id field. Can apparently be fixed by replacing it with id = instance.pk 

Secondly if you send a "create" message through a websocket it will complain that the field "ID" is required.

**Comment by flyboy1565** [comment]
Django's basic behavior is that of you don't include  a primary key, it will add a field called id.. (all lower case). When you add primary key to a field, that removes the need for django to add the id field. 

So it would seem in your case you have created an ID field with primary key.. this should me you can access it doing instance.ID.

I havent tested what you're​ saying, so please take what I'm saying with a grain of sand until you can try it out.

**Comment by luisdemarchi** [comment]
The ideal is to reference the field "id" as "pk", as mentioned by @Patrick-Berg . I made this change directly from my side, since it is taking too long for an approval of something.
