### ISSUE TITLE
Token based Auth

### ISSUE THREAD

**Issue by daesu** [linuxlewis/channels-api#16]
Hi all, 

First thanks for this package. It's very much appreciated. 

Second, I don't seem to be able to figure out the best way to go about authentication for clients using DRF token based auth. (Django OAuth Toolkit)

Any resource I've found on auth seems to focus on session based auth which I guess makes sense from a websocket point of view. 

For my REST api I am sending an Authorization header with an access token as the value. What would you recommend I look into to get this auth working with the channels_api ? 

Thank you

**Comment by linuxlewis** [comment]
Hi there, unfortunately the websocket spec is against you here. The websocket spec doesn't allow for Authorization. There's a variety of ways to work around this but I would think of your websocket authorization as separate from your API authorization.

What I usually do is pass a token via a query arg like so: ```wss://myservice.com/websocket?token={some_token}```

Reference: https://devcenter.heroku.com/articles/websocket-security#authentication-authorization

**Comment by storerjeremy** [comment]
@daesu Did you ever get this working? If so how did you go about it?

**Comment by daesu** [comment]
@storerjeremy I ended up using a third party api (pusher.com) for my needs so I can't help you here sorry.
