### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by royyeah** [linuxlewis/channels-api#2]
Great work man! Any progress / thoughts on permissions? From that point forward it will become useful for me.

**Comment by cho-is** [comment]
+1!

**Comment by luisdemarchi** [comment]
This library is perfect. Unfortunately it lacks permissions, which includes a promise for version 0.4. Is there any information for this version?

**Comment by nwself** [comment]
What is it exactly that you all need regarding permissions?

I'm having success overriding `has_permission(self, user, action, pk)` in my `ResourceBinding` subclass as described [in the Django Channels docs](https://channels.readthedocs.io/en/stable/binding.html#getting-started).

For channels-api, `action` is one of the actions listed [here in the README](https://github.com/linuxlewis/channels-api#resourcebinding).

Return False if a user does not have permissions.

**Comment by linuxlewis** [comment]
My current thought would be to continue down the "rest framework" path and implement a similar API as their [permission classes](http://www.django-rest-framework.org/api-guide/permissions/#permissions). This could be taken to the extreme by allowing users to use their existing Permission classes with channels-api but I'm not sure if that's very useful.

To be more specific this would be adding some sort of `permissions_classes` to `ResourceBinding`.
I'm not exactly sure how this would reconcile with `has_permission` but I'm thinking I would end up ignoring it or using it in the implementation.

**Comment by luisdemarchi** [comment]
I tried to collaborate with the logic that I did for my project, but I could not work in Python 2.7, because it did not find any class. Also I could not get it in Django 1.08, because it ignored the permissions I made.

**Comment by flyboy1565** [comment]
@linuxlewis , I agree with you idea, since the idea you have is to extend the DRF. Using the same auth modules would  be ideal. I was going to add my "users key" as a resource when submitting through the socket.

**Comment by linuxlewis** [comment]
Permissions have been released in 0.4.0
