### ISSUE TITLE
python 2.7

### ISSUE THREAD

**Issue by kodeine** [linuxlewis/channels-api#25]
does it work with py2.7? Or i have to upgrade to py3?

**Comment by theY4Kman** [comment]
The tests [run against Python 2.7](https://travis-ci.org/linuxlewis/channels-api/jobs/247779899) (config [here](https://github.com/linuxlewis/channels-api/blob/master/tox.ini#L3)), so you should be fine. The README is a bit misleading atm :dango:

**Comment by linuxlewis** [comment]
So my thoughts on this is that I will attempt to maintain support for python2.7 but I make no guarantees.

**Comment by kodeine** [comment]
Ill eventually switch to python 3. :)

**Comment by linuxlewis** [comment]
Docs have been updated. closing
