### ISSUE TITLE
Implament a PATCH ResourceBinding to enable Updating a single field

### ISSUE THREAD

**Issue by vCra** [linuxlewis/channels-api#35]
Hi there,
DRF supports HTTP PATCH methods, to support updating a particular part of an existing element. However, within channels-api, they is no such way of updating one field of an object.
Is it possible to create a new resource binding to implement functionality similar to the HTTP PATCH Method?

**Comment by Herst** [comment]
I created a PR implementing it (#30) but maybe it could also be implemented similar to <https://github.com/linuxlewis/channels-api#custom-actions>.

**Comment by linuxlewis** [comment]
This has been released in 0.4.1 Thanks @Herst for the PR.
