### ISSUE TITLE
Query: Python 2.7?

### ISSUE THREAD

**Issue by volundmush** [linuxlewis/channels-api#4]
I notice that channels-api requires Py3 to run according to its requirements.

I'm working on a project that may benefit from it, but the project is held into py2.7 stasis due to some remaining work that needs to be done getting twisted's telnet working on Py3.

So I'm thinking of making tweaks to this so it will run on Py2.7 for my own use.

Still learning the differences between Py3 and so I'm just making a simple question here: what specifically in this code does not work with Py2.7?

**Comment by linuxlewis** [comment]
There's nothing to comes to mind specifically. I would just try it and submit a PR if anything is broken
