### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by kamilgregorczyk** [linuxlewis/channels-api#40]
How would this package behave with, for e.g. 10 replicas of the same server? (both, rest and some websocket server). If a change goes to server 1, will it be received by a consumer which is listening on server 3?

**Comment by hishnash** [comment]
yes, that is handled by Django-channels you will need to set up the Redis layer for this to work but as long as all the servers use the same Redis cluster the events will be sent to all servers.

**Comment by kamilgregorczyk** [comment]
Thanks, issue can be closed.
