### ISSUE TITLE
Incompatible with new Channels 1.0.2

### ISSUE THREAD

**Issue by josip-u** [linuxlewis/channels-api#6]
Channels API is now incompatible with Channels 1.0.2, because of different number of parameters passed to group_names() method. Bug is reproduced by Channels API [example](https://github.com/linuxlewis/channels-api#getting-started). Reproduction:

1. Upgrade Channels to 1.0.2
2. Go to Django Admin and try to create a new instance of some model
3. Channels crashes

Additionally, downgrading Channels to 1.0.1 solves the problem.

**Comment by linuxlewis** [comment]
thanks for the report. This should be fixed in 0.3.1. Releasing as soon as the build passes

**Comment by linuxlewis** [comment]
Released
